Feature: Create Promo code

        Background:
            Given User passes the authorization on "Auth Page"

        Scenario: Create and check Promo code
             When User logins as a "admin"
             Then User is in "Dashboard" page
             When User navigates to "Settings Tab" from "Dashboard Page"
              And User clicks "Promo Codes Tab" on "Settings Page"
              And User clicks "New Promo Code Button" on "Promo Code Page"
              And User selects "GAM Network" from "Channel List Dropdown" on "Promo Code Page"
              And User named Promo code to "Promo Code input" on "Promo Code Page"
              And User selects 1 day for Promo Code duration to "Start Date Input" and "End Date Input" on "Promo Code Page"
              And User selects "Percent" from "Discount Type Dropdown" on "Promo Code Page"
              And User fills "Discount Value Input" as "10" on "Promo Code Page"
              And User fills "Min Budget Input" as "1" on "Promo Code Page"
              And User fills "Max Budget Input" as "999" on "Promo Code Page"
              And User select "USD" from "Currency List Dropdown" on "Promo Code Page"
              And User fills "Code Can Be Used Input" as "1" on "Promo Code Page"
              And User clicks "Save Button" on "Promo Code Page"
              And User clicks "Publish button" for activate Promo Code on "Promo Code Page"
              And User navigates to "Dashboard Tab" from "Dashboard Page"
             When User clicks "Create Campaign Button" on "Dashboard Page"
              And User selects "YM Company" for "Advertiser Type" on "Campaign Wizard Page"
              And User enters "Campaign Name Input" as "Test Automation Campaign" on "Campaign Wizard Page"
              And User clicks "Next Button" on "Campaign Wizard Page"
              And User clicks "Creatives Campaign Type" on "Campaign Wizard Page"
              And User clicks "Display Creative Category" on "Campaign Wizard Page"
              And User clicks "Yahya Test Product" on "Campaign Wizard Page"
              And User clicks "Next Button" on "Campaign Wizard Page"
              And User enters "Total Budget Input" as "10" on "Campaign Wizard Page"
              And User clicks "Next Button" on "Campaign Wizard Page"
              And User clicks "Add Creative Later Button" on "Campaign Wizard Page"
              And User enters "PO Number Input" as "PO123" on "Campaign Wizard page"
              And User clicks "Checkout Button" on "Campaign Wizard Page"
              And User clicks "Add Promo Code Button" on "Campaign Details Page"
             Then User enters Promo Code to "Promo Code Input" on "Campaign Details Page"
              And User clicks "Apply Button" on "Campaign Details Page"
             Then User should see "Discount Info Text" on "Campaign Details Page"